### ISSUE TITLE
Instructions for compiling firmware for wireless upload?

### ISSUE THREAD

**Issue by Patronics** [mattncsu/ESPixelClock#1]
Could you provide instructions (or a link to some) for how to compile the firmware to upload to the clock? 
I've programmed a slight modification to add an option to hide the leading zero digit from the display, which I'll submit as a pull request once I figure out how to compile it and verify that it works. 

Did you use the Arduino IDE directly, or PlatformIO, or something else? Any instructions or tips would be appreciated.

**Comment by Patronics** [comment]
I figured it out, but this project could still benefit from instructions and a list of required libraries. 
Here's a start at documenting the requirements:

Follow these instructions to install the ESP32 boards into the arduino IDE, https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/boards_manager.md

Set the board to "ESP32 Dev module" in the Boards Menu,

install the required libraries, including (but not necessarily limited to)
- FastLED.h
- AsyncTCP.h
- ESPAsyncWebServer.h
- AsyncElegantOTA.h
- DS3231M.h
- SHT21.h

Compile code to verify changes,

Then Go to the _Sketch_ menu > and click _Export Compiled Binary_
Upload the .bin file created using the web UI

**Comment by mattncsu** [comment]
That about sums it up, glad you got it working!
